In [1]:
%matplotlib inline
import numpy as np

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [3]:
type(x)

numpy.ndarray

In [4]:
dir(x)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__delslice__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getslice__',
 '__gt__',
 '__hash__',
 '__hex__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__oct__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__rdivmod__',
 '__reduce__',
 

In [23]:
x.shape

(2, 3)

In [7]:
x.strides

(12, 4)

In [8]:
x.data

<read-write buffer for 0x10c400e90, size 24, offset 0 at 0x10c3e8d70>

In [9]:
x.itemsize

4

In [10]:
x.nbytes

24

In [11]:
x.base

In [12]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [13]:
x.real

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [14]:
x.imag

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [15]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [16]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [17]:
x.flat

In [18]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [19]:
x.ctypes

In [20]:
np.all([[True,False],[True,True]])

False

In [22]:
np.all([[True,False],[True,True]], axis=1)

array([False,  True], dtype=bool)