In [6]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print a[1,2]

6


In [7]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__delslice__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getslice__',
 '__gt__',
 '__hash__',
 '__hex__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__oct__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__rdivmod__',
 '__reduce__',
 

In [17]:
a = np.full((2, 2), 7)

In [18]:
a

array([[ 7.,  7.],
       [ 7.,  7.]])

In [21]:
a = np.arange(12)

In [22]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
a.reshape((3, 2, 2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [30]:
a = np.array([[1,2],[3,4],[5,6]])
b = a*2
print b

[[ 2  4]
 [ 6  8]
 [10 12]]


In [32]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = np.array([0,2,0,1])

In [33]:
print a[np.arange(4),b]

[ 1  6  7 11]


In [34]:
a = np.array([ [1, 2, 3], [4,5,6]])

In [35]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
b = np.array([[1, 2], [2, 3], [4, 5]])

In [37]:
b

array([[1, 2],
       [2, 3],
       [4, 5]])

In [38]:
a.shape

(2, 3)

In [39]:
b.shape

(3, 2)

In [40]:
c = np.dot(a, b)

In [41]:
c

array([[17, 23],
       [38, 53]])